
# name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     types:
#       - completed

# jobs:

#   build:

#     runs-on: self-hosted

#     steps:
#     - name: Pull Docker image
#       run: sudo docker pull winkohtun/assignmentfrontend:latest
#     - name: Delete Old docker container
#       run: sudo docker rm -f assignmentfrontend-container || true
#     - name: Run Docker Container
#       run: sudo docker run -d -p 8080:8080 --name assignmentfrontend-container winkohtun/assignmentfrontend


name: CD Pipeline Frontend

on:
  workflow_run:
    workflows: ["CI Pipeline Frontend"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image d
        run: sudo docker pull winkohtun/assignmentfrontend:latest
      - name: Delete Old docker container
        run: sudo docker rm -f assignmentfrontend-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name assignmentfrontend-container winkohtun/assignmentfrontend
