
name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Login DockerHub ddddd
      env : 
        DOCKER_USERNAME : ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
      run : docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Pull Docker image
      run: sudo docker pull winkohtun/assignmentfrontend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f assignmentfrontend-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name assignmentfrontend-container winkohtun/assignmentfrontend
