# name: CI Pipeline

# on:
#   push:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Login DockerHub
#       env : 
#         DOCKER_USERNAME : ${{secrets.DOCKER_USERNAME}}
#         DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
#       run : docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#     - name: Build the Docker image
#       run: docker build -t winkohtun/assignmentfrontend .
#     - name: Push to Dockerhub
#       run: docker push winkohtun/assignmentfrontend:latest


name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login DockerHub
      env : 
        DOCKER_USERNAME : ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
      run : docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t winkohtun/assignmentfrontend .
    - name: Push to Dockerhub
      run: docker push winkohtun/assignmentfrontend:latest
    - name: Pull Docker image
      run: sudo docker pull winkohtun/assignmentfrontend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f assignmentfrontend-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name assignmentfrontend-container winkohtun/assignmentfrontend
